kind: Service
apiVersion: v1
metadata:
  name: esearchservice
  labels:
    app: esearch
spec:
  selector:
    app: esearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node